name: compass
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_compass: ^0.8.1
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.10

flutter_icons:
  android: true
  ios: true
  image_path: "lib/images/icon.png"

flutter_native_splash:
  color: "#EFF3F6"            # Light theme background
  color_dark: "#2D2F33"       # Dark theme background
  image: lib/images/icon.png
  image_dark: lib/images/icon.png
  android: true
  ios: true
  web: false


flutter:
  uses-material-design: true

  assets:
    - lib/images/

